version: '3.9'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis/redis-stack:7.4.0-v3
    ports:
      - "6379:6379"

